### ISSUE TITLE
Can not work on Mac OS webui, pls help !

### ISSUE THREAD

**Issue by laichaoyi** [GeorgLegato/stable-diffusion-webui-vectorstudio#1]
can not work on Mac OS webUI: 

Error loading script: vectorstudio.py
Traceback (most recent call last):
  File "/Users/andyle/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/andyle/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/andyle/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 42, in <module>
    from tkinter import Image, image_types
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by GeorgLegato** [comment]
import tkinter removed from code 
fixed
