### ISSUE TITLE
Potrace problems under windows

### ISSUE THREAD

**Issue by mykeehu** [GeorgLegato/stable-diffusion-webui-vectorstudio#25]
There are two problems with potrace. First it said that 32 bit version cannot be used, and I got this error (and the code says it downloads 64 bits, I don't understand):
```
Traceback (most recent call last):
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio\scripts\vectorstudio.py", line 215, in run
        self.doVector(poFormat, poOpaque, poTight, poKeepPnm, poThreshold, PO_TO_CALL, img, fullofpnm, fullof, mixedImages)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio\scripts\vectorstudio.py", line 231, in doVector
        p2 = subprocess.Popen(args)
      File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    OSError: [WinError 216] A(z) %1 verziója nem kompatibilis a telepített Windows rendszerrel. Ellenőrizze a rendszerinformációkat, majd lépjen kapcsolatba a szoftver gyártójával

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 700, in run
        processed = script.run(p, *script_args)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-vectorstudio\scripts\vectorstudio.py", line 218, in run
        raise Exception("VectorStudio: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)")
    Exception: VectorStudio: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)
```

After I downloaded the 64-bit potrace, then I got this error, it can't handle the path (is cv2.imwrite or cv2.imread in the code? In my experience it does not handle windows routes well, you should use the PIL Image function instead):
```
I:\Stable-Diffusion-Automatic\stable-diffusion-webui
Total progress: 60it [03:22,  3.37s/it]
Traceback (most recent call last):it/s]
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\components\gallery.py", line 203, in postprocess
    file_path = self.make_temp_copy_if_needed(img)
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'I:\\Stable-Diffusion-Automatic\\generated\\txt2img-images\\19815-3146272705.svg'
```

**Comment by mykeehu** [comment]
Ok, after restart full webui, I didn't get any error. Sorry for issue, have a nice day!
