### ISSUE TITLE
ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by froger-me** [GeorgLegato/stable-diffusion-webui-vectorstudio#4]
On windows:

```
[stablediffusion_install_dir]\webui-user.bat
```

```
Already up to date.
venv "[stablediffusion_install_dir]\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI


Launching Web UI with arguments: --xformers
Error loading script: pngsvg.py
Traceback (most recent call last):
  File "[stablediffusion_install_dir]\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "[stablediffusion_install_dir]\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "[stablediffusion_install_dir]\extensions\stable-diffusion-webui-vectorstudio\scripts\pngsvg.py", line 2, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

....
```

```
pip show lxml
```

```
Name: lxml
Version: 4.9.2
Summary: Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
Home-page: https://lxml.de/
Author: lxml dev team
Author-email: lxml-dev@lxml.de
License: BSD-3-Clause
Location: c:\python310\lib\site-packages
Requires:
Required-by:
```

Could you please advise?

**Comment by GeorgLegato** [comment]
error in the repository, this file is not supposed to be here. i fix in 1 minute.

**Comment by GeorgLegato** [comment]
please update your extension, the file pngsvg.py must be deleted by this update
