### ISSUE TITLE
problem with POTRACE

### ISSUE THREAD

**Issue by protrading104** [GeorgLegato/stable-diffusion-webui-vectorstudio#8]
I'm trying to run this on Colab. What could be the issue? 

![image](https://user-images.githubusercontent.com/71656833/232231030-473637ec-93f0-43f9-a6d1-b3ab0983e293.png)

![image](https://user-images.githubusercontent.com/71656833/232231059-7eac14b3-ecbd-4033-88d1-a6009c2bbd81.png)

![image](https://user-images.githubusercontent.com/71656833/232231086-c5c6bbc3-7a67-48f2-98c3-087731710490.png)

**Comment by GeorgLegato** [comment]
I had never any success from anyone on collabs. I ve never tested collabs;  I think a collab is a foreign environment with constraints etc.
actually your setup looks good, but check if images are saved at all. could be collabs have different setting. the extension is post-processing stored images. btw, if collabd and collab "somewhere" (not on your machine"). do you knoe the underlaying os? is an win-executable right? or has it to be a linux one?

**Comment by protrading104** [comment]
crap, yes its linux ))
linux cant read potrace.exe.

but SD works fine in normal mode (without scripts)

i need to get an SVG, but is there a way to do it without potrace.exe? Your Txt2Vectorgraphics script is very good. it's a pity you don't support him more.

**Comment by GeorgLegato** [comment]
you need to download the potrace for linux, copy it into the bin or create a softllink, as stated in the place_potrace_here.txt

**Comment by seetvael** [comment]
can you explain in more detail which version to download. What changes need to make for Colab?
Im download this https://potrace.sourceforge.net/download/1.16/potrace-1.16.linux-x86_64.tar.gz
but same problem.


<scripts.external_code.ControlNetUnit object at 0x7fdd19d7c2b0>, <scripts.external_code.ControlNetUnit object at 0x7fdd05200520>, <scripts.external_code.ControlNetUnit object at 0x7fdd052006d0>, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, 50, 'Illustration', 'svg', True, True, False, 0.5, False, 16, True, 16) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 140, in run
    self.doVector(poFormat, poOpaque, poTight, poKeepPnm, poThreshold, PO_TO_CALL, img, fullofpnm, fullof, mixedImages)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 156, in doVector
    p2 = subprocess.Popen(args)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/stable-diffusion-webui-vectorstudio/bin/potrace.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 399, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 143, in run
    raise Exception("TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)")
Exception: TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)

**Comment by osmania101** [comment]
Error completing request
Arguments: ('task(ko1kg4z49b1jv2l)', 'a cat, vector base,', 'blurry', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 5, <controlnet.py.UiControlNetUnit object at 0x2b06377c0>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, 50, 'Illustration', 'svg', True, True, False, 0.5, False, 16, True, 16) {}
Traceback (most recent call last):
  File "/Users/london/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 140, in run
    self.doVector(poFormat, poOpaque, poTight, poKeepPnm, poThreshold, PO_TO_CALL, img, fullofpnm, fullof, mixedImages)
  File "/Users/london/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 156, in doVector
    p2 = subprocess.Popen(args)
  File "/Users/london/anaconda3/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/london/anaconda3/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/stable-diffusion-webui-vectorstudio/bin/potrace.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/london/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/london/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/london/stable-diffusion-webui/modules/txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/Users/london/stable-diffusion-webui/modules/scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "/Users/london/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/scripts/vectorstudio.py", line 143, in run
    raise Exception("TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)")
Exception: TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)


the same problem

**Comment by samueljacobjackson** [comment]
This worked for me in my colab.
```
if potrace:
  ! apt install potrace -y
  ! ln -s /bin/potrace /{data_dir}/stable-diffusion-webui/extensions/stable-diffusion-webui-vectorstudio/bin/potrace.exe
```

**Comment by GeorgLegato** [comment]
even on Linux or MAC os, the binary potrace file needs to be named "potrace.exe"
this is a simply not to differ on which os we are etc. not handling PATH, OS-Type, Pakcages, Dowload stuff.
